log failure

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -25,9 +25,12 @@ function download_version() {
   tmpdir=$(get_temp_dir)
   trap "rm -rf $tmpdir" EXIT
 
-  echo "Downloading Bun v$version..."
-  curl -sSfLo "$tmpdir/bun.zip" "$bin_url" || fail "Couldn't download the Bun binary from $bin_url"
-  unzip -q -j "$tmpdir/bun.zip" "bun-$platform-$arch/bun" -d "$download_path"
+  (
+    echo "Downloading Bun v$version..."
+    curl -sSfLo "$tmpdir/bun.zip" "$bin_url" || fail "Couldn't download the Bun binary from $bin_url"
+
+    unzip -j "$tmpdir/bun.zip" "bun-$platform-$arch/bun" -d "$download_path"
+  ) || (rm -rf "$download_path"; fail "Failed to download Bun v$version")
 }
 
 if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -22,7 +22,7 @@ function install_version() {
     chmod +x "$install_path/bin/bun"
 
     echo "Bun v$version is installed successfully!"
-  ) || (rm -rf "$install_path"; exit 1)
+  ) || (rm -rf "$install_path"; fail "Failed to install Bun v$version")
 }
 
 if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
